import { secureInt } from "@/lib/random";
import {
  DICE_TOTAL_SUMS,
  type DiceRollMode,
  type DiceSecret,
  type PublicDiceState,
} from "@/lib/games/types";

// Dice Sweep engine. Three dice per turn — collect every total from 3 to 18
// in any order; repeating a total you already collected ends the game.
//
// Each turn the player chooses to roll ALL remaining dice at once or ONE die
// at a time (more suspense). Every die is generated server-side AT ROLL TIME
// with a CSPRNG — future dice never exist anywhere before the roll.

export function startDice(): { secret: DiceSecret; progress: number } {
  return { secret: { collected: [], pending: [] }, progress: 0 };
}

export interface DiceRollResult {
  /** Dice generated by THIS call (1 for "one", up to 3 for "all"). */
  rolled: number[];
  /** All dice in the current turn after this call. */
  turnDice: number[];
  turnComplete: boolean;
  /** Set only when the turn completes: */
  sum?: number;
  collectedSum?: boolean; // true = new total banked, false = repeat = loss
  newProgress: number;
  won: boolean;
  lost: boolean;
}

/** Mutates `secret` (pending dice / collected totals). */
export function applyDiceRoll(secret: DiceSecret, mode: DiceRollMode): DiceRollResult {
  const toRoll = mode === "one" ? 1 : 3 - secret.pending.length;
  const rolled: number[] = [];
  for (let i = 0; i < toRoll; i++) rolled.push(secureInt(6) + 1);
  secret.pending.push(...rolled);

  if (secret.pending.length < 3) {
    // Turn still in progress — nothing to evaluate yet.
    return {
      rolled,
      turnDice: [...secret.pending],
      turnComplete: false,
      newProgress: secret.collected.length,
      won: false,
      lost: false,
    };
  }

  const turnDice = [...secret.pending];
  const sum = turnDice.reduce((a, b) => a + b, 0);
  const repeat = secret.collected.includes(sum);
  if (!repeat) secret.collected.push(sum);
  secret.pending = [];

  const newProgress = secret.collected.length;
  const won = !repeat && newProgress === DICE_TOTAL_SUMS;
  return {
    rolled,
    turnDice,
    turnComplete: true,
    sum,
    collectedSum: !repeat,
    newProgress,
    won,
    lost: repeat,
  };
}

export function dicePublicState(
  secret: DiceSecret,
  lastTurn: { dice: number[]; sum: number; collected: boolean } | null
): PublicDiceState {
  return {
    collected: [...secret.collected],
    sumsCollected: secret.collected.length,
    totalSums: DICE_TOTAL_SUMS,
    pending: [...secret.pending],
    lastTurn,
  };
}
